version: "3.9"

name: focusflow-dev

networks:
  focusflow-net:

volumes:
  pg_data:
  kafka_data:

services:
  postgres:
    image: postgres:16-alpine
    container_name: ff-postgres
    environment:
      POSTGRES_DB: focusflow
      POSTGRES_USER: focusflow
      POSTGRES_PASSWORD: focusflow
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U focusflow -d focusflow"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - focusflow-net

  redis:
    image: redis:7-alpine
    container_name: ff-redis
    command: ["redis-server", "--appendonly", "no"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 15
    networks:
      - focusflow-net

  # Kafka senza ZooKeeper (KRaft)
  kafka:
    image: bitnami/kafka:3.7
    container_name: ff-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 15
    networks:
      - focusflow-net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Comoda UI per ispezionare Kafka (opzionale ma utile)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ff-kafka-ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - focusflow-net
